services:
  - type: worker
    name: discord-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: AIML_API_KEY
        sync: false
      - key: HUGGING_FACE_TOKEN
        sync: false
      - key: PORT
        value: "8000"
        sync: false
        
